holds = []
bursts = []
mines = []

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[receptors]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
pressed_color = [
    0.8000000715255737,
    0.800000011920929,
    1.0,
    1.0,
]
image = "5.png"

[receptors.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "3.png"

[notes.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "4.png"

[notes.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "ln.png"

[notes.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "3.png"

[notes.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "4.png"

[notes.size]
x = 90.0
y = 90.0

[[notes]]
color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
image = "ln.png"

[notes.size]
x = 90.0
y = 90.0
