# Configuration du skin pour 8 colonnes
[skin]
name = "Default 8K"
version = "1.0.0"
author = "RVSRG"

font = "font.ttf"
[images]
receptor = "receptor.png"
# receptor_0 = "receptor_col0.png"
# receptor_1 = "receptor_col1.png"
# receptor_2 = "receptor_col2.png"
# receptor_3 = "receptor_col3.png"
# receptor_4 = "receptor_col4.png"
# receptor_5 = "receptor_col5.png"
# receptor_6 = "receptor_col6.png"
# receptor_7 = "receptor_col7.png"

note = "note.png"
# note_0 = "note_col0.png"
# note_1 = "note_col1.png"
# note_2 = "note_col2.png"
# note_3 = "note_col3.png"
# note_4 = "note_col4.png"
# note_5 = "note_col5.png"
# note_6 = "note_col6.png"
# note_7 = "note_col7.png"

miss_note = "miss_note.png"
background = "background.png"

[colors]
receptor_color = [0.0, 0.0, 1.0, 1.0]
note_color = [1.0, 1.0, 1.0, 1.0]
marv = [0.0, 1.0, 1.0, 1.0]
perfect = [1.0, 1.0, 0.0, 1.0]
great = [0.0, 1.0, 0.0, 1.0]
good = [0.0, 0.0, 0.5, 1.0]
bad = [1.0, 0.41, 0.71, 1.0]
miss = [1.0, 0.0, 0.0, 1.0]
ghost_tap = [0.5, 0.5, 0.5, 1.0]

[keys]
column_0 = ["KeyA"]
column_1 = ["KeyS"]
column_2 = ["KeyD"]
column_3 = ["KeyF"]
column_4 = ["KeyH"]
column_5 = ["KeyJ"]
column_6 = ["KeyK"]
column_7 = ["KeyL"]

[ui_positions]
